name: Build FastVanish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FastVanish
        path: target/FastVanish-*.jar
        retention-days: 30
        
    - name: Verify JAR contents
      run: |
        echo "Checking JAR contents..."
        jar -tf target/FastVanish-*.jar | head -20
        echo "Build completed successfully!" 